In [1]:
import pandas as pd

In [2]:
d={
    "movies": [
        "Katara", "KGF", "Dhamal", "sinna", "PK",
        "Golmal", "Dhurandar", "Salaar", "Rush", "Bahubali"
    ],

    "rating": [
        10, 8, 10, 5, 7,
        None, 2, 8, None, 6
    ],

    "language_year": ["Hindi-2026","Kannada-2018","Hindi-2007","Telugu-2024","Hindi-2014",
    "Hindi-2006","Hindi-2025","Telugu-2023","Hindi-2012","Telugu-2015"
],

    "cast": [
        ["Rishabh", "Vaishnavi"],["Yash", "Srinidhi"],["Sanjay", "karishma"],["Aamir Khan", "Genelia Deshmukh"],
        ["Aamir", "Anushka"],["Ajay", "kareena"],["Ranveer", "Sara"],["Prabhas", "Shruti"],["Emraan", "Neha"],["Prabhas", "Anushka"]
    ],

    "hotstar": [
        1, 1, 1, 0, 0,
        1, 0, 1, 1, 0
    ],

    "netflix": [
        "no", "yes", "yes", "no", "yes",
        "no", "yes", "no", "yes", "no"
    ]
}

print(d)

{'movies': ['Katara', 'KGF', 'Dhamal', 'sinna', 'PK', 'Golmal', 'Dhurandar', 'Salaar', 'Rush', 'Bahubali'], 'rating': [10, 8, 10, 5, 7, None, 2, 8, None, 6], 'language_year': ['Hindi-2026', 'Kannada-2018', 'Hindi-2007', 'Telugu-2024', 'Hindi-2014', 'Hindi-2006', 'Hindi-2025', 'Telugu-2023', 'Hindi-2012', 'Telugu-2015'], 'cast': [['Rishabh', 'Vaishnavi'], ['Yash', 'Srinidhi'], ['Sanjay', 'karishma'], ['Aamir Khan', 'Genelia Deshmukh'], ['Aamir', 'Anushka'], ['Ajay', 'kareena'], ['Ranveer', 'Sara'], ['Prabhas', 'Shruti'], ['Emraan', 'Neha'], ['Prabhas', 'Anushka']], 'hotstar': [1, 1, 1, 0, 0, 1, 0, 1, 1, 0], 'netflix': ['no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no', 'yes', 'no']}

Tables = Dataframe

Columns = series

In [3]:
# d
# pd.DataFrame(d)
df=pd.DataFrame(d)

In [4]:
df

,movies,rating,language_year,cast,hotstar,netflix
0,Katara,10.0,Hindi-2026,"[Rishabh, Vaishnavi]",1,no
1,KGF,8.0,Kannada-2018,"[Yash, Srinidhi]",1,yes
2,Dhamal,10.0,Hindi-2007,"[Sanjay, karishma]",1,yes
3,sinna,5.0,Telugu-2024,"[Aamir Khan, Genelia Deshmukh]",0,no
4,PK,7.0,Hindi-2014,"[Aamir, Anushka]",0,yes
5,Golmal,NaN,Hindi-2006,"[Ajay, kareena]",1,no
6,Dhurandar,2.0,Hindi-2025,"[Ranveer, Sara]",0,yes
7,Salaar,8.0,Telugu-2023,"[Prabhas, Shruti]",1,no
8,Rush,NaN,Hindi-2012,"[Emraan, Neha]",1,yes
9,Bahubali,6.0,Telugu-2015,"[Prabhas, Anushka]",0,no

In [5]:
# df.head()        # it will display 5 records(default value=5)
# df.head(2)       # it will display first 2 record
df.head(4)       # it will display first 4 record

,movies,rating,language_year,cast,hotstar,netflix
0,Katara,10.0,Hindi-2026,"[Rishabh, Vaishnavi]",1,no
1,KGF,8.0,Kannada-2018,"[Yash, Srinidhi]",1,yes
2,Dhamal,10.0,Hindi-2007,"[Sanjay, karishma]",1,yes
3,sinna,5.0,Telugu-2024,"[Aamir Khan, Genelia Deshmukh]",0,no

In [6]:
df.tail()     # it will display last 5 record (Default value=5)
df.tail(3)    # It will display last 3 record
df.tail(2)    # It will display last 2 record

     movies  rating language_year                cast  hotstar netflix
8      Rush     NaN    Hindi-2012      [Emraan, Neha]        1     yes
9  Bahubali     6.0   Telugu-2015  [Prabhas, Anushka]        0      no

In [7]:
df.info()    # It will give the summary of the table

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   movies         10 non-null     str
 1   rating         8 non-null      float64
 2   language_year  10 non-null     str
 3   cast           10 non-null     object
 4   hotstar        10 non-null     int64
 5   netflix        10 non-null     str
dtypes: float64(1), int64(1), object(1), str(3)
memory usage: 612.0+ bytes

In [8]:
df.columns       # It is use for select all the columns in the dataframe
df['rating']     # Used to display a perticular column (syntax= Dataframe[col_name]) col_name is present in the 1D(1-dimension)
df["netflix"]
# df["cast",'netflix']         # KeyError we can only pass 1 parameter because it is 1D

0     no
1    yes
2    yes
3     no
4    yes
5     no
6    yes
7     no
8    yes
9     no
Name: netflix, dtype: str

In [9]:
    # Syntax=Dataframe[['column1',"column2",.........]]

df[["movies","cast"]]

      movies                            cast
0     Katara            [Rishabh, Vaishnavi]
1        KGF                [Yash, Srinidhi]
2     Dhamal              [Sanjay, karishma]
3      sinna  [Aamir Khan, Genelia Deshmukh]
4         PK                [Aamir, Anushka]
5     Golmal                 [Ajay, kareena]
6  Dhurandar                 [Ranveer, Sara]
7     Salaar               [Prabhas, Shruti]
8       Rush                  [Emraan, Neha]
9   Bahubali              [Prabhas, Anushka]

In [10]:
df['movies'].str.title()         # !st latter in the capital form

0       Katara
1          Kgf
2       Dhamal
3        Sinna
4           Pk
5       Golmal
6    Dhurandar
7       Salaar
8         Rush
9     Bahubali
Name: movies, dtype: str

In [11]:
df['Movies']=df['movies'].str.title()   # it will create new Movies column

In [12]:
df

,movies,rating,language_year,cast,hotstar,netflix,Movies
0,Katara,10.0,Hindi-2026,"[Rishabh, Vaishnavi]",1,no,Katara
1,KGF,8.0,Kannada-2018,"[Yash, Srinidhi]",1,yes,Kgf
2,Dhamal,10.0,Hindi-2007,"[Sanjay, karishma]",1,yes,Dhamal
3,sinna,5.0,Telugu-2024,"[Aamir Khan, Genelia Deshmukh]",0,no,Sinna
4,PK,7.0,Hindi-2014,"[Aamir, Anushka]",0,yes,Pk
5,Golmal,NaN,Hindi-2006,"[Ajay, kareena]",1,no,Golmal
6,Dhurandar,2.0,Hindi-2025,"[Ranveer, Sara]",0,yes,Dhurandar
7,Salaar,8.0,Telugu-2023,"[Prabhas, Shruti]",1,no,Salaar
8,Rush,NaN,Hindi-2012,"[Emraan, Neha]",1,yes,Rush
9,Bahubali,6.0,Telugu-2015,"[Prabhas, Anushka]",0,no,Bahubali

In [13]:
df=df.drop(columns=['movies'])      # Delete the perticular column this is non permanent

In [14]:
df  # Assigning data into variable we can delete data permanently

,rating,language_year,cast,hotstar,netflix,Movies
0,10.0,Hindi-2026,"[Rishabh, Vaishnavi]",1,no,Katara
1,8.0,Kannada-2018,"[Yash, Srinidhi]",1,yes,Kgf
2,10.0,Hindi-2007,"[Sanjay, karishma]",1,yes,Dhamal
3,5.0,Telugu-2024,"[Aamir Khan, Genelia Deshmukh]",0,no,Sinna
4,7.0,Hindi-2014,"[Aamir, Anushka]",0,yes,Pk
5,NaN,Hindi-2006,"[Ajay, kareena]",1,no,Golmal
6,2.0,Hindi-2025,"[Ranveer, Sara]",0,yes,Dhurandar
7,8.0,Telugu-2023,"[Prabhas, Shruti]",1,no,Salaar
8,NaN,Hindi-2012,"[Emraan, Neha]",1,yes,Rush
9,6.0,Telugu-2015,"[Prabhas, Anushka]",0,no,Bahubali

In [15]:
df['language_year'].str.title()   # This change is temparary

df['Language_year']=df['language_year'].str.title()  # Add new column
df['language_year']=df['language_year'].str.title()  # update the present column
df

,rating,language_year,cast,hotstar,netflix,Movies,Language_year
0,10.0,Hindi-2026,"[Rishabh, Vaishnavi]",1,no,Katara,Hindi-2026
1,8.0,Kannada-2018,"[Yash, Srinidhi]",1,yes,Kgf,Kannada-2018
2,10.0,Hindi-2007,"[Sanjay, karishma]",1,yes,Dhamal,Hindi-2007
3,5.0,Telugu-2024,"[Aamir Khan, Genelia Deshmukh]",0,no,Sinna,Telugu-2024
4,7.0,Hindi-2014,"[Aamir, Anushka]",0,yes,Pk,Hindi-2014
5,NaN,Hindi-2006,"[Ajay, kareena]",1,no,Golmal,Hindi-2006
6,2.0,Hindi-2025,"[Ranveer, Sara]",0,yes,Dhurandar,Hindi-2025
7,8.0,Telugu-2023,"[Prabhas, Shruti]",1,no,Salaar,Telugu-2023
8,NaN,Hindi-2012,"[Emraan, Neha]",1,yes,Rush,Hindi-2012
9,6.0,Telugu-2015,"[Prabhas, Anushka]",0,no,Bahubali,Telugu-2015

In [16]:
df.drop(columns="language_year")       # This is tempary Change
df=df.drop(columns="language_year")     # Data is parmanently deleted
df

,rating,cast,hotstar,netflix,Movies,Language_year
0,10.0,"[Rishabh, Vaishnavi]",1,no,Katara,Hindi-2026
1,8.0,"[Yash, Srinidhi]",1,yes,Kgf,Kannada-2018
2,10.0,"[Sanjay, karishma]",1,yes,Dhamal,Hindi-2007
3,5.0,"[Aamir Khan, Genelia Deshmukh]",0,no,Sinna,Telugu-2024
4,7.0,"[Aamir, Anushka]",0,yes,Pk,Hindi-2014
5,NaN,"[Ajay, kareena]",1,no,Golmal,Hindi-2006
6,2.0,"[Ranveer, Sara]",0,yes,Dhurandar,Hindi-2025
7,8.0,"[Prabhas, Shruti]",1,no,Salaar,Telugu-2023
8,NaN,"[Emraan, Neha]",1,yes,Rush,Hindi-2012
9,6.0,"[Prabhas, Anushka]",0,no,Bahubali,Telugu-2015

In [17]:
df['rating']=df['rating'].fillna(1)          # This is tempary Change

In [18]:
df

,rating,cast,hotstar,netflix,Movies,Language_year
0,10.0,"[Rishabh, Vaishnavi]",1,no,Katara,Hindi-2026
1,8.0,"[Yash, Srinidhi]",1,yes,Kgf,Kannada-2018
2,10.0,"[Sanjay, karishma]",1,yes,Dhamal,Hindi-2007
3,5.0,"[Aamir Khan, Genelia Deshmukh]",0,no,Sinna,Telugu-2024
4,7.0,"[Aamir, Anushka]",0,yes,Pk,Hindi-2014
5,1.0,"[Ajay, kareena]",1,no,Golmal,Hindi-2006
6,2.0,"[Ranveer, Sara]",0,yes,Dhurandar,Hindi-2025
7,8.0,"[Prabhas, Shruti]",1,no,Salaar,Telugu-2023
8,1.0,"[Emraan, Neha]",1,yes,Rush,Hindi-2012
9,6.0,"[Prabhas, Anushka]",0,no,Bahubali,Telugu-2015

In [19]:
df=df.replace({'yes':1,'no':0})
df

,rating,cast,hotstar,netflix,Movies,Language_year
0,10.0,"[Rishabh, Vaishnavi]",1,0,Katara,Hindi-2026
1,8.0,"[Yash, Srinidhi]",1,1,Kgf,Kannada-2018
2,10.0,"[Sanjay, karishma]",1,1,Dhamal,Hindi-2007
3,5.0,"[Aamir Khan, Genelia Deshmukh]",0,0,Sinna,Telugu-2024
4,7.0,"[Aamir, Anushka]",0,1,Pk,Hindi-2014
5,1.0,"[Ajay, kareena]",1,0,Golmal,Hindi-2006
6,2.0,"[Ranveer, Sara]",0,1,Dhurandar,Hindi-2025
7,8.0,"[Prabhas, Shruti]",1,0,Salaar,Telugu-2023
8,1.0,"[Emraan, Neha]",1,1,Rush,Hindi-2012
9,6.0,"[Prabhas, Anushka]",0,0,Bahubali,Telugu-2015

In [20]:
df["Language_year"].str.split('-')

0      [Hindi, 2026]
1    [Kannada, 2018]
2      [Hindi, 2007]
3     [Telugu, 2024]
4      [Hindi, 2014]
5      [Hindi, 2006]
6      [Hindi, 2025]
7     [Telugu, 2023]
8      [Hindi, 2012]
9     [Telugu, 2015]
Name: Language_year, dtype: object

In [21]:
df[['Language','year']]=df["Language_year"].str.split('-', expand=True)

In [22]:
df

,rating,cast,hotstar,netflix,Movies,Language_year,Language,year
0,10.0,"[Rishabh, Vaishnavi]",1,0,Katara,Hindi-2026,Hindi,2026
1,8.0,"[Yash, Srinidhi]",1,1,Kgf,Kannada-2018,Kannada,2018
2,10.0,"[Sanjay, karishma]",1,1,Dhamal,Hindi-2007,Hindi,2007
3,5.0,"[Aamir Khan, Genelia Deshmukh]",0,0,Sinna,Telugu-2024,Telugu,2024
4,7.0,"[Aamir, Anushka]",0,1,Pk,Hindi-2014,Hindi,2014
5,1.0,"[Ajay, kareena]",1,0,Golmal,Hindi-2006,Hindi,2006
6,2.0,"[Ranveer, Sara]",0,1,Dhurandar,Hindi-2025,Hindi,2025
7,8.0,"[Prabhas, Shruti]",1,0,Salaar,Telugu-2023,Telugu,2023
8,1.0,"[Emraan, Neha]",1,1,Rush,Hindi-2012,Hindi,2012
9,6.0,"[Prabhas, Anushka]",0,0,Bahubali,Telugu-2015,Telugu,2015

In [23]:
df=df.drop(columns=["Language_year"])
df

,rating,cast,hotstar,netflix,Movies,Language,year
0,10.0,"[Rishabh, Vaishnavi]",1,0,Katara,Hindi,2026
1,8.0,"[Yash, Srinidhi]",1,1,Kgf,Kannada,2018
2,10.0,"[Sanjay, karishma]",1,1,Dhamal,Hindi,2007
3,5.0,"[Aamir Khan, Genelia Deshmukh]",0,0,Sinna,Telugu,2024
4,7.0,"[Aamir, Anushka]",0,1,Pk,Hindi,2014
5,1.0,"[Ajay, kareena]",1,0,Golmal,Hindi,2006
6,2.0,"[Ranveer, Sara]",0,1,Dhurandar,Hindi,2025
7,8.0,"[Prabhas, Shruti]",1,0,Salaar,Telugu,2023
8,1.0,"[Emraan, Neha]",1,1,Rush,Hindi,2012
9,6.0,"[Prabhas, Anushka]",0,0,Bahubali,Telugu,2015

# loc[row(mendatary),column(optional)]      
Used for selecting row as well as column

In [24]:
df.loc[0]

rating                      10.0
cast        [Rishabh, Vaishnavi]
hotstar                        1
netflix                        0
Movies                    Katara
Language                   Hindi
year                        2026
Name: 0, dtype: object

In [25]:
df.loc[[0,1,5]]

   rating                  cast  hotstar netflix  Movies Language  year
0    10.0  [Rishabh, Vaishnavi]        1       0  Katara    Hindi  2026
1     8.0      [Yash, Srinidhi]        1       1     Kgf  Kannada  2018
5     1.0       [Ajay, kareena]        1       0  Golmal    Hindi  2006

In [26]:
df.loc[[0,1,5],["Movies"]]      # In the loc() method we can pass  df.loc[row/list of row, col/list of col]

   Movies
0  Katara
1     Kgf
5  Golmal

In [27]:
df.loc[[0,1,5],["Movies","rating","hotstar"]]

   Movies  rating  hotstar
0  Katara    10.0        1
1     Kgf     8.0        1
5  Golmal     1.0        1

In [28]:
print(df['hotstar']==1)             # Movies present in the hotstar

0     True
1     True
2     True
3    False
4    False
5     True
6    False
7     True
8     True
9    False
Name: hotstar, dtype: bool

In [29]:
print(df['Language']=="Hindi")       # return only hindi language movie

0     True
1    False
2     True
3    False
4     True
5     True
6     True
7    False
8     True
9    False
Name: Language, dtype: bool

# loc[condition,list of column]
using of condition    we use &(And)  or |(or)

In [30]:

df.loc[(df['hotstar']==1) & (df['Language']=="Hindi")]

   rating                  cast  hotstar netflix  Movies Language  year
0    10.0  [Rishabh, Vaishnavi]        1       0  Katara    Hindi  2026
2    10.0    [Sanjay, karishma]        1       1  Dhamal    Hindi  2007
5     1.0       [Ajay, kareena]        1       0  Golmal    Hindi  2006
8     1.0        [Emraan, Neha]        1       1    Rush    Hindi  2012

In [31]:
df

,rating,cast,hotstar,netflix,Movies,Language,year
0,10.0,"[Rishabh, Vaishnavi]",1,0,Katara,Hindi,2026
1,8.0,"[Yash, Srinidhi]",1,1,Kgf,Kannada,2018
2,10.0,"[Sanjay, karishma]",1,1,Dhamal,Hindi,2007
3,5.0,"[Aamir Khan, Genelia Deshmukh]",0,0,Sinna,Telugu,2024
4,7.0,"[Aamir, Anushka]",0,1,Pk,Hindi,2014
5,1.0,"[Ajay, kareena]",1,0,Golmal,Hindi,2006
6,2.0,"[Ranveer, Sara]",0,1,Dhurandar,Hindi,2025
7,8.0,"[Prabhas, Shruti]",1,0,Salaar,Telugu,2023
8,1.0,"[Emraan, Neha]",1,1,Rush,Hindi,2012
9,6.0,"[Prabhas, Anushka]",0,0,Bahubali,Telugu,2015

In [32]:
df=df.astype ({'year':'int'})    # astype function used to convert  one type data into anoyher type of data

In [33]:
df.loc[(df['year']==2023) | (df['year']==2025)]

   rating               cast  hotstar netflix     Movies Language  year
6     2.0    [Ranveer, Sara]        0       1  Dhurandar    Hindi  2025
7     8.0  [Prabhas, Shruti]        1       0     Salaar   Telugu  2023

In [34]:
df.info()        # Before using astype function datatype(year) == object tha

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rating    10 non-null     float64
 1   cast      10 non-null     object
 2   hotstar   10 non-null     int64
 3   netflix   10 non-null     object
 4   Movies    10 non-null     str
 5   Language  10 non-null     str
 6   year      10 non-null     int64
dtypes: float64(1), int64(2), object(2), str(2)
memory usage: 692.0+ bytes

# Melt Function

used for apply aggregate function such as min,max,count,sum,mean

for converting into row

syntax= pd.melt(Data, id_vars= , value_vars= , var_name= , value_name=)

id_vars = columns to remain same

value_vars = The columns to change into rows

var_name = New name for the old columns

value_name = column name for the values

In [35]:
pd.melt(df,value_vars=['hotstar','netflix'])

   variable value
0   hotstar     1
1   hotstar     1
2   hotstar     1
3   hotstar     0
4   hotstar     0
5   hotstar     1
6   hotstar     0
7   hotstar     1
8   hotstar     1
9   hotstar     0
10  netflix     0
11  netflix     1
12  netflix     1
13  netflix     0
14  netflix     1
15  netflix     0
16  netflix     1
17  netflix     0
18  netflix     1
19  netflix     0

In [36]:
pd.melt(df,id_vars=['Movies','rating'],value_vars=['hotstar','netflix'])

       Movies  rating variable value
0      Katara    10.0  hotstar     1
1         Kgf     8.0  hotstar     1
2      Dhamal    10.0  hotstar     1
3       Sinna     5.0  hotstar     0
4          Pk     7.0  hotstar     0
5      Golmal     1.0  hotstar     1
6   Dhurandar     2.0  hotstar     0
7      Salaar     8.0  hotstar     1
8        Rush     1.0  hotstar     1
9    Bahubali     6.0  hotstar     0
10     Katara    10.0  netflix     0
11        Kgf     8.0  netflix     1
12     Dhamal    10.0  netflix     1
13      Sinna     5.0  netflix     0
14         Pk     7.0  netflix     1
15     Golmal     1.0  netflix     0
16  Dhurandar     2.0  netflix     1
17     Salaar     8.0  netflix     0
18       Rush     1.0  netflix     1
19   Bahubali     6.0  netflix     0

In [37]:
pd.melt(df,id_vars=['Movies','rating'],value_vars=['hotstar','netflix'], var_name="Platform")

       Movies  rating Platform value
0      Katara    10.0  hotstar     1
1         Kgf     8.0  hotstar     1
2      Dhamal    10.0  hotstar     1
3       Sinna     5.0  hotstar     0
4          Pk     7.0  hotstar     0
5      Golmal     1.0  hotstar     1
6   Dhurandar     2.0  hotstar     0
7      Salaar     8.0  hotstar     1
8        Rush     1.0  hotstar     1
9    Bahubali     6.0  hotstar     0
10     Katara    10.0  netflix     0
11        Kgf     8.0  netflix     1
12     Dhamal    10.0  netflix     1
13      Sinna     5.0  netflix     0
14         Pk     7.0  netflix     1
15     Golmal     1.0  netflix     0
16  Dhurandar     2.0  netflix     1
17     Salaar     8.0  netflix     0
18       Rush     1.0  netflix     1
19   Bahubali     6.0  netflix     0

In [38]:
df1=pd.melt(df,id_vars=['Movies','rating'],value_vars=['hotstar','netflix'], var_name="Platform",value_name="Avilability")

df1       # new table that we created

       Movies  rating Platform Avilability
0      Katara    10.0  hotstar           1
1         Kgf     8.0  hotstar           1
2      Dhamal    10.0  hotstar           1
3       Sinna     5.0  hotstar           0
4          Pk     7.0  hotstar           0
5      Golmal     1.0  hotstar           1
6   Dhurandar     2.0  hotstar           0
7      Salaar     8.0  hotstar           1
8        Rush     1.0  hotstar           1
9    Bahubali     6.0  hotstar           0
10     Katara    10.0  netflix           0
11        Kgf     8.0  netflix           1
12     Dhamal    10.0  netflix           1
13      Sinna     5.0  netflix           0
14         Pk     7.0  netflix           1
15     Golmal     1.0  netflix           0
16  Dhurandar     2.0  netflix           1
17     Salaar     8.0  netflix           0
18       Rush     1.0  netflix           1
19   Bahubali     6.0  netflix           0

In [39]:
df1=df1.loc[df1['Avilability']==1]
df1

       Movies  rating Platform Avilability
0      Katara    10.0  hotstar           1
1         Kgf     8.0  hotstar           1
2      Dhamal    10.0  hotstar           1
5      Golmal     1.0  hotstar           1
7      Salaar     8.0  hotstar           1
8        Rush     1.0  hotstar           1
11        Kgf     8.0  netflix           1
12     Dhamal    10.0  netflix           1
14         Pk     7.0  netflix           1
16  Dhurandar     2.0  netflix           1
18       Rush     1.0  netflix           1

In [40]:
df1=df1.reset_index(drop=True)
df1

       Movies  rating Platform Avilability
0      Katara    10.0  hotstar           1
1         Kgf     8.0  hotstar           1
2      Dhamal    10.0  hotstar           1
3      Golmal     1.0  hotstar           1
4      Salaar     8.0  hotstar           1
5        Rush     1.0  hotstar           1
6         Kgf     8.0  netflix           1
7      Dhamal    10.0  netflix           1
8          Pk     7.0  netflix           1
9   Dhurandar     2.0  netflix           1
10       Rush     1.0  netflix           1

In [41]:
df1=df1.drop(columns=['Avilability'])
df1

       Movies  rating Platform
0      Katara    10.0  hotstar
1         Kgf     8.0  hotstar
2      Dhamal    10.0  hotstar
3      Golmal     1.0  hotstar
4      Salaar     8.0  hotstar
5        Rush     1.0  hotstar
6         Kgf     8.0  netflix
7      Dhamal    10.0  netflix
8          Pk     7.0  netflix
9   Dhurandar     2.0  netflix
10       Rush     1.0  netflix

# Convert Data file in csv formate

df.to_csv('filename.csv')

In [42]:
df.to_csv('movies.csv')

In [43]:
df.to_csv('movies.csv' ,index=False)        # index=False for delete the extra columns

In [44]:
# pip install openpyxl

In [45]:
df.to_excel('movies.xlsx',index=False)

# Aggregate fuctions

In [46]:
df1['rating'].agg('max')

np.float64(10.0)

In [47]:
df1['rating'].agg(['max','min'])

max    10.0
min     1.0
Name: rating, dtype: float64

In [48]:
df1.agg({'rating':'max','Movies':'count'})

rating    10.0
Movies    11.0
dtype: float64

In [49]:
df1.agg({'rating':['max','min'],'Movies':'count'})

       rating  Movies
max      10.0     NaN
min       1.0     NaN
count     NaN    11.0

# Group by

In [50]:
df1.groupby('Platform')

In [51]:
df1.groupby('Platform').agg('count')

          Movies  rating
Platform
hotstar        6       6
netflix        5       5

In [52]:
df1.groupby('Platform').agg({'rating':"max","Movies":'count'})

          rating  Movies
Platform
hotstar     10.0       6
netflix     10.0       5